# -*- coding: utf-8 -*-
"""OSS_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1db4JyqbDFpNRlw0zqYQqzg4kjldHrmaS
"""

from sklearn import datasets

wine=datasets.load_wine()
print(wine.data.shape)
print(wine.target_names)